
build:
	javac -classpath src/flanagan.jar:src src/readtest/*
clean:

package: 

test: 
	java -cp src/flanagan.jar:src/ /course/cs4500wc/Examples/foo.mp3 /course/cs4500wc/Examples/foo.wav

.PHONY: build clean package test

